from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.patches import FancyArrowPatch, FancyBboxPatch, Rectangle


FIG_DIR = Path("figures")
FIG_DIR.mkdir(exist_ok=True)


def box(ax, x, y, w, h, text, fc="#f8fafc", ec="#334155", size=8):
    patch = FancyBboxPatch(
        (x, y),
        w,
        h,
        boxstyle="round,pad=0.02,rounding_size=0.035",
        linewidth=1.1,
        edgecolor=ec,
        facecolor=fc,
    )
    ax.add_patch(patch)
    ax.text(x + w / 2, y + h / 2, text, ha="center", va="center", fontsize=size, wrap=True)


def arrow(ax, x1, y1, x2, y2):
    ax.add_patch(
        FancyArrowPatch(
            (x1, y1),
            (x2, y2),
            arrowstyle="->",
            mutation_scale=10,
            linewidth=1,
            color="#475569",
        )
    )


def setup_ax(figsize=(8, 4.8)):
    fig, ax = plt.subplots(figsize=figsize, dpi=220)
    ax.set_xlim(0, 10)
    ax.set_ylim(0, 6)
    ax.axis("off")
    return fig, ax


def save(fig, name):
    fig.tight_layout(pad=0.4)
    fig.savefig(FIG_DIR / name, bbox_inches="tight")
    plt.close(fig)


def system_architecture():
    fig, ax = setup_ax()
    ax.text(5, 5.7, "AgriConnect+ System Architecture", ha="center", fontsize=12, weight="bold")

    box(ax, 0.3, 4.55, 2.0, 0.75, "User Inputs\nstate, district, crop,\nirrigation, acres, years", "#e0f2fe")
    box(ax, 0.3, 3.2, 2.0, 0.75, "Data Sources\nprice, yield,\nlease rates, costs", "#ecfccb")
    box(ax, 3.0, 4.45, 2.1, 0.85, "XGBoost Layer\nprice model\nyield model\ndecision model", "#fef3c7")
    box(ax, 3.0, 3.0, 2.1, 0.85, "Rule-Based Engine\nyield conversion\nincome formulas", "#fee2e2")
    box(ax, 5.8, 3.75, 2.0, 0.85, "Decision Logic\nfarm vs lease\nrisk level", "#ede9fe")
    box(ax, 8.3, 3.75, 1.4, 0.85, "Dashboard\ncharts, what-if,\nreports", "#dcfce7")

    arrow(ax, 2.3, 4.9, 3.0, 4.9)
    arrow(ax, 2.3, 3.55, 3.0, 3.45)
    arrow(ax, 5.1, 4.85, 5.8, 4.35)
    arrow(ax, 5.1, 3.45, 5.8, 4.0)
    arrow(ax, 7.8, 4.18, 8.3, 4.18)
    save(fig, "system_architecture.png")


def training_pipeline():
    fig, ax = setup_ax((8, 4.4))
    ax.text(5, 5.35, "Model Training and Inference Pipeline", ha="center", fontsize=12, weight="bold")

    box(ax, 0.35, 4.15, 1.65, 0.7, "Raw Data\nCSV + JSON", "#e0f2fe")
    box(ax, 2.35, 4.15, 1.65, 0.7, "Preprocess\nclean + encode", "#f1f5f9")
    box(ax, 4.35, 4.15, 1.65, 0.7, "Train Models\nXGBoost", "#fef3c7")
    box(ax, 6.35, 4.15, 1.65, 0.7, "Evaluate\nR2, MAE, F1", "#ecfccb")
    box(ax, 8.25, 4.15, 1.35, 0.7, "Save\njoblib", "#ede9fe")

    box(ax, 1.0, 2.35, 1.75, 0.7, "Dashboard\ninput case", "#dcfce7")
    box(ax, 3.35, 2.35, 1.75, 0.7, "Load Models\nor fallback", "#f8fafc")
    box(ax, 5.7, 2.35, 1.75, 0.7, "Predict\nprice + yield", "#fef3c7")
    box(ax, 8.0, 2.35, 1.45, 0.7, "Compute\nrecommendation", "#fee2e2")

    for x in [2.0, 4.0, 6.0, 8.0]:
        arrow(ax, x, 4.5, x + 0.35, 4.5)
    arrow(ax, 8.9, 4.15, 8.9, 3.05)
    arrow(ax, 2.75, 2.7, 3.35, 2.7)
    arrow(ax, 5.1, 2.7, 5.7, 2.7)
    arrow(ax, 7.45, 2.7, 8.0, 2.7)
    save(fig, "training_pipeline.png")


def model_architecture():
    fig, ax = setup_ax((8, 4.6))
    ax.text(5, 5.45, "Hybrid Model Architecture", ha="center", fontsize=12, weight="bold")

    box(ax, 0.25, 4.25, 1.6, 0.68, "Price Features\nstate, district,\ncrop", "#e0f2fe")
    box(ax, 0.25, 3.15, 1.6, 0.68, "Yield Features\nstate, crop,\nirrigation", "#dcfce7")
    box(ax, 0.25, 2.05, 1.6, 0.68, "Decision Features\nprice, yield,\ncost, lease", "#fef3c7")

    box(ax, 2.55, 4.25, 1.9, 0.68, "XGBRegressor\nPrice Model", "#fef3c7")
    box(ax, 2.55, 3.15, 1.9, 0.68, "XGBRegressor\nYield Model", "#fef3c7")
    box(ax, 2.55, 2.05, 1.9, 0.68, "XGBClassifier\nDecision Model", "#fef3c7")

    box(ax, 5.25, 3.2, 1.9, 0.85, "Rule-Based\nEconomic Engine\nTc, Tl, D", "#fee2e2")
    box(ax, 7.85, 3.2, 1.65, 0.85, "Final Output\nincome report\nrecommendation", "#ede9fe")

    arrow(ax, 1.85, 4.58, 2.55, 4.58)
    arrow(ax, 1.85, 3.48, 2.55, 3.48)
    arrow(ax, 1.85, 2.38, 2.55, 2.38)
    arrow(ax, 4.45, 4.58, 5.25, 3.9)
    arrow(ax, 4.45, 3.48, 5.25, 3.65)
    arrow(ax, 4.45, 2.38, 5.25, 3.35)
    arrow(ax, 7.15, 3.62, 7.85, 3.62)

    ax.text(5.25, 1.05, "Decision model learns the economic decision boundary generated by the rule engine.", fontsize=8, ha="center")
    save(fig, "model_architecture.png")


def dashboard_input_demo():
    fig, ax = setup_ax((8, 4.4))
    ax.text(5, 5.35, "Dashboard Input Demonstration", ha="center", fontsize=12, weight="bold")

    panel = FancyBboxPatch((0.7, 0.85), 8.6, 3.9, boxstyle="round,pad=0.03,rounding_size=0.04",
                           linewidth=1.2, edgecolor="#334155", facecolor="#f8fafc")
    ax.add_patch(panel)
    ax.text(1.05, 4.45, "Step 1 - Enter Farm Details", fontsize=10, weight="bold", color="#1e293b")

    labels = [
        ("State", "Karnataka"),
        ("District", "Bangalore"),
        ("Crop", "Rice"),
        ("Irrigation", "Irrigated"),
        ("Duration", "3 years"),
        ("Land Size", "2 acres"),
        ("Market Scenario", "Average"),
        ("Lease Rate", "Rs. 40,000 / acre / year"),
    ]

    x_positions = [1.05, 3.25, 5.45, 7.35]
    y_positions = [3.55, 2.35]
    idx = 0
    for y in y_positions:
        for x in x_positions:
            if idx >= len(labels):
                break
            label, value = labels[idx]
            ax.text(x, y + 0.45, label, fontsize=7.5, color="#475569", weight="bold")
            ax.add_patch(Rectangle((x, y), 1.55 if x < 7 else 1.8, 0.35,
                                   linewidth=0.9, edgecolor="#cbd5e1", facecolor="white"))
            ax.text(x + 0.08, y + 0.18, value, fontsize=7, va="center", color="#0f172a")
            idx += 1

    ax.add_patch(FancyBboxPatch((4.0, 1.25), 2.0, 0.5, boxstyle="round,pad=0.02,rounding_size=0.04",
                                linewidth=0, facecolor="#2563eb"))
    ax.text(5.0, 1.5, "Generate Report", ha="center", va="center", fontsize=8, color="white", weight="bold")
    save(fig, "dashboard_input_demo.png")


def report_demo():
    fig, ax = setup_ax((8, 4.9))
    ax.text(5, 5.65, "Generated Income Report Demonstration", ha="center", fontsize=12, weight="bold")

    panel = FancyBboxPatch((0.55, 0.55), 8.9, 4.65, boxstyle="round,pad=0.03,rounding_size=0.04",
                           linewidth=1.2, edgecolor="#334155", facecolor="#ffffff")
    ax.add_patch(panel)
    ax.text(0.95, 4.85, "Rice - Bangalore, Karnataka - 2 acres - 3 years", fontsize=9, weight="bold")

    cards = [
        ("Crop Income", "Rs. 4,34,404", "#dcfce7"),
        ("Lease Income", "Rs. 2,40,000", "#ffedd5"),
        ("Advantage", "Rs. 1,94,404", "#dbeafe"),
        ("Best Option", "Crop Farming", "#ede9fe"),
    ]
    x = 0.9
    for title, value, color in cards:
        ax.add_patch(FancyBboxPatch((x, 3.82), 1.85, 0.65, boxstyle="round,pad=0.02,rounding_size=0.04",
                                    linewidth=0.8, edgecolor="#cbd5e1", facecolor=color))
        ax.text(x + 0.12, 4.25, title, fontsize=7.2, color="#475569", weight="bold")
        ax.text(x + 0.12, 3.98, value, fontsize=8.5, color="#0f172a", weight="bold")
        x += 2.05

    ax.add_patch(Rectangle((0.95, 2.0), 3.2, 1.25, linewidth=0.8, edgecolor="#cbd5e1", facecolor="#f8fafc"))
    ax.text(1.1, 3.05, "Model Outputs", fontsize=8, weight="bold")
    ax.text(1.1, 2.75, "Predicted price: Rs. 4627.62 / quintal", fontsize=7)
    ax.text(1.1, 2.48, "Predicted yield: 2519.33 kg / ha", fontsize=7)
    ax.text(1.1, 2.21, "Decision confidence: 99.77%", fontsize=7)

    ax.add_patch(Rectangle((4.55, 2.0), 3.9, 1.25, linewidth=0.8, edgecolor="#cbd5e1", facecolor="#f8fafc"))
    ax.text(4.7, 3.05, "Recommendation", fontsize=8, weight="bold")
    ax.text(4.7, 2.72, "Crop farming is preferred for this case.", fontsize=7.3)
    ax.text(4.7, 2.45, "Estimated advantage over leasing: 81.00%.", fontsize=7.3)
    ax.text(4.7, 2.18, "Source: trained models + economic engine.", fontsize=7.3)

    ax.add_patch(Rectangle((0.95, 0.95), 7.5, 0.55, linewidth=0.8, edgecolor="#cbd5e1", facecolor="#eff6ff"))
    ax.text(1.1, 1.25, "Report includes charts, what-if sliders, year-wise income table, and downloadable CSV/text outputs.", fontsize=7.2)
    save(fig, "report_demo.png")


if __name__ == "__main__":
    system_architecture()
    model_architecture()
    training_pipeline()
    dashboard_input_demo()
    report_demo()
    print("Generated paper figures in figures/")
